[2025-07-24T16:51:15.770+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T16:51:15.803+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.load_song_dim_table manual__2025-07-24T16:50:52.440427+00:00 [queued]>
[2025-07-24T16:51:15.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.load_song_dim_table manual__2025-07-24T16:50:52.440427+00:00 [queued]>
[2025-07-24T16:51:15.815+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-24T16:51:15.843+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_song_dim_table> on 2025-07-24 16:50:52.440427+00:00
[2025-07-24T16:51:15.873+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'load_song_dim_table', 'manual__2025-07-24T16:50:52.440427+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmpvjq4m8q9']
[2025-07-24T16:51:15.876+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask load_song_dim_table
[2025-07-24T16:51:15.878+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=8057) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-24T16:51:15.880+0000] {standard_task_runner.py:64} INFO - Started process 8063 to run task
[2025-07-24T16:51:15.905+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-24T16:51:15.943+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.load_song_dim_table manual__2025-07-24T16:50:52.440427+00:00 [running]> on host da6b6b72382b
[2025-07-24T16:51:16.078+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='load_song_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T16:50:52.440427+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T16:50:52.440427+00:00'
[2025-07-24T16:51:16.083+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T16:51:16.208+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T16:51:16.209+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 182, in _run
    cur.execute(query)
psycopg2.errors.UndefinedColumn: column "song_id" of relation "songs" does not exist
LINE 2:         insert into songs(song_id,title,artist_id, year,dura...
                                  ^

[2025-07-24T16:51:16.226+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=load_song_dim_table, run_id=manual__2025-07-24T16:50:52.440427+00:00, execution_date=20250724T165052, start_date=20250724T165115, end_date=20250724T165116
[2025-07-24T16:51:16.245+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task load_song_dim_table (column "song_id" of relation "songs" does not exist
LINE 2:         insert into songs(song_id,title,artist_id, year,dura...
                                  ^
; 8063)
[2025-07-24T16:51:16.264+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-24T16:51:16.277+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
