[2025-07-25T01:47:49.372+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T01:47:49.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.load_songplays_face_table scheduled__2025-07-24T00:00:00+00:00 [queued]>
[2025-07-25T01:47:49.412+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.load_songplays_face_table scheduled__2025-07-24T00:00:00+00:00 [queued]>
[2025-07-25T01:47:49.412+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2025-07-25T01:47:49.428+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_songplays_face_table> on 2025-07-24 00:00:00+00:00
[2025-07-25T01:47:49.436+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4631) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T01:47:49.435+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'load_songplays_face_table', 'scheduled__2025-07-24T00:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmppzztbphy']
[2025-07-25T01:47:49.437+0000] {standard_task_runner.py:64} INFO - Started process 4632 to run task
[2025-07-25T01:47:49.437+0000] {standard_task_runner.py:91} INFO - Job 164: Subtask load_songplays_face_table
[2025-07-25T01:47:49.456+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-25T01:47:49.489+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.load_songplays_face_table scheduled__2025-07-24T00:00:00+00:00 [running]> on host da6b6b72382b
[2025-07-25T01:47:49.565+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='load_songplays_face_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T00:00:00+00:00'
[2025-07-25T01:47:49.566+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T01:47:49.779+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T01:47:49.780+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 185, in _run
    cur.execute(query)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "songplays_pkey"
DETAIL:  Key (playid)=(e30eb65b5ce5534fed9764a7996916ec) already exists.

[2025-07-25T01:47:49.790+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=load_songplays_face_table, run_id=scheduled__2025-07-24T00:00:00+00:00, execution_date=20250724T000000, start_date=20250725T014749, end_date=20250725T014749
[2025-07-25T01:47:49.804+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 164 for task load_songplays_face_table (duplicate key value violates unique constraint "songplays_pkey"
DETAIL:  Key (playid)=(e30eb65b5ce5534fed9764a7996916ec) already exists.
; 4632)
[2025-07-25T01:47:49.812+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-25T01:47:49.831+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T01:47:49.835+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
