[2025-07-22T10:27:03.193+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T10:27:05.273+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.load_song_dim_table manual__2025-07-22T10:16:36.248466+00:00 [queued]>
[2025-07-22T10:27:05.590+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.load_song_dim_table manual__2025-07-22T10:16:36.248466+00:00 [queued]>
[2025-07-22T10:27:05.616+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-22T10:27:06.595+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_song_dim_table> on 2025-07-22 10:16:36.248466+00:00
[2025-07-22T10:27:07.920+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'load_song_dim_table', 'manual__2025-07-22T10:16:36.248466+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmp7h7q2p27']
[2025-07-22T10:27:08.307+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask load_song_dim_table
[2025-07-22T10:27:08.323+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1729) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-22T10:27:08.340+0000] {standard_task_runner.py:64} INFO - Started process 1752 to run task
[2025-07-22T10:27:10.929+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-22T10:27:13.490+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.load_song_dim_table manual__2025-07-22T10:16:36.248466+00:00 [running]> on host 2ad5d09a42d7
[2025-07-22T10:27:16.980+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='load_song_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T10:16:36.248466+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T10:16:36.248466+00:00'
[2025-07-22T10:27:17.063+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T10:27:25.658+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T10:27:25.692+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 149, in _run
    conn = psycopg2.connect(**conn_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "hainam" to address: Temporary failure in name resolution

[2025-07-22T10:27:25.996+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=load_song_dim_table, run_id=manual__2025-07-22T10:16:36.248466+00:00, execution_date=20250722T101636, start_date=20250722T102705, end_date=20250722T102725
[2025-07-22T10:27:26.241+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task load_song_dim_table (could not translate host name "hainam" to address: Temporary failure in name resolution
; 1752)
[2025-07-22T10:27:26.303+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-22T10:27:26.426+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-22T10:27:26.437+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
