[2025-07-24T14:45:36.259+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T14:45:36.317+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl_test.stage_eventss manual__2025-07-24T14:45:31.436015+00:00 [queued]>
[2025-07-24T14:45:36.328+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl_test.stage_eventss manual__2025-07-24T14:45:31.436015+00:00 [queued]>
[2025-07-24T14:45:36.329+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-24T14:45:36.351+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_eventss> on 2025-07-24 14:45:31.436015+00:00
[2025-07-24T14:45:36.359+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1501) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-24T14:45:36.360+0000] {standard_task_runner.py:64} INFO - Started process 1502 to run task
[2025-07-24T14:45:36.371+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl_test', 'stage_eventss', 'manual__2025-07-24T14:45:31.436015+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmph9fa75fy']
[2025-07-24T14:45:36.377+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask stage_eventss
[2025-07-24T14:45:36.408+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-24T14:45:36.444+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl_test.stage_eventss manual__2025-07-24T14:45:31.436015+00:00 [running]> on host da6b6b72382b
[2025-07-24T14:45:36.576+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl_test' AIRFLOW_CTX_TASK_ID='stage_eventss' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T14:45:31.436015+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T14:45:31.436015+00:00'
[2025-07-24T14:45:36.577+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T14:45:36.605+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T14:45:36.607+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_log_data_to_table() missing 1 required positional argument: 'file_dir'
[2025-07-24T14:45:36.628+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=tunestream_etl_test, task_id=stage_eventss, run_id=manual__2025-07-24T14:45:31.436015+00:00, execution_date=20250724T144531, start_date=20250724T144536, end_date=20250724T144536
[2025-07-24T14:45:36.647+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task stage_eventss (load_log_data_to_table() missing 1 required positional argument: 'file_dir'; 1502)
[2025-07-24T14:45:36.656+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-24T14:45:36.683+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T14:45:36.690+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
