[2025-07-22T09:11:32.741+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T09:11:32.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.stage_songs manual__2025-07-22T09:11:27.349803+00:00 [queued]>
[2025-07-22T09:11:32.953+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.stage_songs manual__2025-07-22T09:11:27.349803+00:00 [queued]>
[2025-07-22T09:11:32.955+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-22T09:11:33.018+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_songs> on 2025-07-22 09:11:27.349803+00:00
[2025-07-22T09:11:33.033+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'stage_songs', 'manual__2025-07-22T09:11:27.349803+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmpv2jj8v1w']
[2025-07-22T09:11:33.038+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask stage_songs
[2025-07-22T09:11:33.039+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=7583) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-22T09:11:33.040+0000] {standard_task_runner.py:64} INFO - Started process 7584 to run task
[2025-07-22T09:11:33.068+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-22T09:11:33.142+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.stage_songs manual__2025-07-22T09:11:27.349803+00:00 [running]> on host 7b3eb14378b0
[2025-07-22T09:11:33.415+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T09:11:27.349803+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T09:11:27.349803+00:00'
[2025-07-22T09:11:33.418+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T09:11:33.507+0000] {logging_mixin.py:188} INFO - tổng số file json tìm được là 0
[2025-07-22T09:11:41.648+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T09:11:41.736+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 28, in load_song_data_to_table
    connect = psycopg2.connect(**conn_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "hainam" to address: Temporary failure in name resolution

[2025-07-22T09:11:42.316+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=stage_songs, run_id=manual__2025-07-22T09:11:27.349803+00:00, execution_date=20250722T091127, start_date=20250722T091132, end_date=20250722T091142
[2025-07-22T09:11:42.381+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task stage_songs (could not translate host name "hainam" to address: Temporary failure in name resolution
; 7584)
[2025-07-22T09:11:42.471+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-22T09:11:42.588+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-22T09:11:42.605+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
